name: Unit Test
on: 
  push: 
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered on branch ${{ github.ref }}."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit test
        run: python cli.py -e all

      - run: echo "🍏 This job's status is ${{ job.status }}."
